all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.110, mac: '70:85:c2:20:f4:a6', disk: sda, network_interface: enp0s31f6}
    workers:
      hosts:
